[package]
name = "enkei"
version = "0.1.0"
authors = ["Johannes Wünsche <johannes@spacesnek.rocks>"]
description = "A wayland wallpaper tool with support for GNOME dynamic wallpapers"
homepage = "https://git.spacesnek.rocks/johannes/enkei"
repository = "https://git.spacesnek.rocks/johannes/enkei"
categories = ["command-line-utilities", "multimedia:images", "multimedia"]
readme = "README.md"
license = "MIT"
keywords = ["sway", "wlroots", "wallpaper", "background", "gnome"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
cairo-rs = { version = "0.9.1", features = ["png"] }
chrono = "0.4.19"
clap = "2.33.3"
ezing = "0.2.1"
gdk = "0.13.2"
gio = "0.9.1"
glib = "0.10.3"
gtk = "0.9.2"
gtk-layer-shell = "0.2.0"
image = "0.23.14"
log = "0.4.14"
regex = "1.5.4"
serde = { version = "1.0.125", features = ["derive"] }
serde-xml-rs = "0.4.1"

[package.metadata.rpm]
package = "enkei"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
enkei = { path = "/usr/bin/enkei" }
