[package]
name = "enkei"
version = "0.1.0"
authors = ["Johannes Wünsche <johannes@spacesnek.rocks>"]
description = "A modern wallpaper tool with support for GNOME dynamic wallpapers"
edition = "2018"

[dependencies]
anyhow = "1.0.40"
cairo-rs = { version = "0.9.1", features = ["png"] }
chrono = "0.4.19"
clap = "2.33.3"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
gio = "0.9.1"
glib = "0.10.3"
gtk = "0.9.2"
gtk-layer-shell = "0.2.0"
log = "0.4.14"
serde = { version = "1.0.125", features = ["derive"] }
serde-xml-rs = "0.4.1"
wayland-client = "0.28.5"
# gtk-layer-shell-rs = { git = "https://github.com/subgraph/gtk-layer-shell-rs" }
# gtk = { git = "https://github.com/gtk-rs/gtk4-rs", package = "gtk4" }
