[package]
name = "enkei"
version = "0.1.1"
authors = ["Johannes Wünsche <johannes@spacesnek.rocks>"]
description = "A wayland wallpaper tool with support for GNOME dynamic wallpapers"
homepage = "https://git.spacesnek.rocks/johannes/enkei"
repository = "https://git.spacesnek.rocks/johannes/enkei"
categories = ["command-line-utilities", "multimedia:images", "multimedia"]
readme = "README.md"
license = "MIT"
keywords = ["sway", "wlroots", "wallpaper", "background", "gnome"]
edition = "2018"

[dependencies]
anyhow = "1.0.43"
cairo-rs = { version = "0.14.3", features = ["png"] }
chrono = "0.4.19"
clap = "2.33.3"
env_logger = "0.9.0"
ezing = "0.2.1"
gdk = { version = "0.14.0", features = ["v3_22"] }
gio = "0.14.3"
glib = "0.14.4"
gtk = "0.14.1"
gtk-layer-shell = "0.2.2"
image = "0.23.14"
lazy-regex = "2.2.1"
log = "0.4.14"
regex = "1.5.4"
serde = { version = "1.0.129", features = ["derive"] }
serde-xml-rs = "0.5.0"

[package.metadata.rpm]
package = "enkei"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
enkei = { path = "/usr/bin/enkei" }
